import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import NextTopLoader from 'nextjs-toploader';
import { ThemeProvider } from './components/ui/theme-provider';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const satoshi = localFont({
  src: './fonts/Satoshi-Variable.ttf',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="#7c3aed" showSpinner={false} />
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
